name: Add to project

on:
  issues:
    types:
      - opened
        

      
jobs:
  add_to_techdebt:      
      env:
        techdebt_label: 'Полоса: Техдолг'
      runs-on: ubuntu-latest
      steps:    
      - if: ${{ contains(github.event.issue.labels.*.name, env.techdebt_label) }} 
        uses: alex-page/github-project-automation-plus@v0.2.2
        with:
          project: Test
          column: To do
          repo-token: ${{ secrets.GH_TOKEN }}
